### ISSUE TITLE
🌈 Rework colors; Fix Bootstrap layout or any CSS rule for an eye pleasing design

### ISSUE THREAD

**Issue by bacloud23** [bacloud23/open-listings-rep#4]
- I made colours out of my taste. Not good 👎 .
- I think I know what `responsive` is meant to be ...  but nothing more (flexbox ? 😵‍💫 )  on phones? Not good 😥

Any designer 👨‍🎨 with a fine touch 🎨 could help this 🥇 
Keep it flat and simple (no flashy colours please!) 🌈 
Check [Coolors](https://coolors.co/palettes/trending) or others for a 10 colors set

**Check**

Color schemes [tutorial](https://hookagency.com/website-color-schemes/)

**Comment by Anushlinux** [comment]
Hey I am a frontend dev I would like to revamp the ui based on your demands can you pls assign the issue to me

**Comment by vverma022** [comment]
I suggest introducing Shadcn Ui and using tailwind css. Can I be. assigned this issue under Hacktoberfest

**Comment by bacloud23** [comment]
Hi @vverma022 
why would you use it VS using the existing bootstrap.css ?

**Comment by vverma022** [comment]
Better faster and scalable. Codebase can be changed.

**Comment by bacloud23** [comment]
I think it is overkill, bootstrap.css is fine.
you are free to tweak or build on it if you want ^^

**Comment by MINEGHOST007** [comment]
I can help with that if you don't have an issue.

**Comment by bacloud23** [comment]
one by one. i assigned you the other one first ^^

**Comment by bacloud23** [comment]
go for it @Anushlinux can you deliver today ? Hacktoberfest is running fast

**Comment by Anushlinux** [comment]
> go for it @Anushlinux can you deliver today ? Hacktoberfest is running fast

Ok i can do it but first can you discuss with me what exact changes you require wrt to color or ui?
